// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfmOb1f6SqT4NA0Fumf97S2T6nUIkdBlA',
    appId: '1:576532236412:android:f0790a635151fbb07661f9',
    messagingSenderId: '576532236412',
    projectId: 'vectora-project',
    storageBucket: 'vectora-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs6ocYsoO6TQt2nBFPcVEjPbJlfZE-aTM',
    appId: '1:576532236412:ios:28683574676645497661f9',
    messagingSenderId: '576532236412',
    projectId: 'vectora-project',
    storageBucket: 'vectora-project.firebasestorage.app',
    androidClientId: '576532236412-iuqspcrc8gpn3mettraoqdon5bk5barj.apps.googleusercontent.com',
    iosClientId: '576532236412-skkd6c4erj2ucudfqhmopvsfmbibpjv6.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiPersonalContentApp',
  );
}
