// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/search/entities/content_embeddings_entity.dart';
import 'features/search/entities/contents_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 8128517059530730439),
    name: 'ContentsEntity',
    lastPropertyId: const obx_int.IdUid(11, 3958599634335642310),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4477680068727594361),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8541846223891484466),
        name: 'contentId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(3, 6128275674696169974),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5490205527152645946),
        name: 'path',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8084546902900067378),
        name: 'contentName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7188378916750765211),
        name: 'extension',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7316635918900473199),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6397007733832590907),
        name: 'contentSizeInBytes',
        type: 5,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 6533562283901859741),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 3299448024628878195),
        name: 'updatedAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2791187969336182065),
        name: 'imageDescription',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 3958599634335642310),
        name: 'scannedImageTexts',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 6761161346725710068),
    name: 'ContentEmbeddingsEntity',
    lastPropertyId: const obx_int.IdUid(4, 8765777697624316136),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5470824457609560259),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4979798275116237355),
        name: 'contentId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 3605497587856684358),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 6436470048979430510),
        name: 'contentVectors',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(5, 9172710413250616416),
        hnswParams: obx_int.ModelHnswParams(dimensions: 512, distanceType: 2),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8765777697624316136),
        name: 'contentType',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(6, 7746834619786622742),
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 6761161346725710068),
    lastIndexId: const obx_int.IdUid(6, 7746834619786622742),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [6423172255409896124],
    retiredIndexUids: const [],
    retiredPropertyUids: const [
      6325179138622283954,
      7425859078920400728,
      5883576386038801653,
    ],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ContentsEntity: obx_int.EntityDefinition<ContentsEntity>(
      model: _entities[0],
      toOneRelations: (ContentsEntity object) => [],
      toManyRelations: (ContentsEntity object) => {},
      getId: (ContentsEntity object) => object.id,
      setId: (ContentsEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ContentsEntity object, fb.Builder fbb) {
        final contentIdOffset = fbb.writeString(object.contentId);
        final pathOffset = fbb.writeString(object.path);
        final contentNameOffset = fbb.writeString(object.contentName);
        final extensionOffset = fbb.writeString(object.extension);
        final typeOffset = fbb.writeString(object.type);
        final imageDescriptionOffset = object.imageDescription == null
            ? null
            : fbb.writeString(object.imageDescription!);
        final scannedImageTextsOffset = object.scannedImageTexts == null
            ? null
            : fbb.writeString(object.scannedImageTexts!);
        fbb.startTable(12);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, contentIdOffset);
        fbb.addOffset(2, pathOffset);
        fbb.addOffset(3, contentNameOffset);
        fbb.addOffset(4, extensionOffset);
        fbb.addOffset(5, typeOffset);
        fbb.addInt32(6, object.contentSizeInBytes);
        fbb.addInt64(7, object.createdAt.millisecondsSinceEpoch);
        fbb.addInt64(8, object.updatedAt?.millisecondsSinceEpoch);
        fbb.addOffset(9, imageDescriptionOffset);
        fbb.addOffset(10, scannedImageTextsOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final updatedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          20,
        );
        final contentIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final pathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final contentNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final imageDescriptionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 22);
        final scannedImageTextsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 24);
        final contentSizeInBytesParam = const fb.Int32Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final extensionParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0),
        );
        final updatedAtParam = updatedAtValue == null
            ? null
            : DateTime.fromMillisecondsSinceEpoch(updatedAtValue);
        final object = ContentsEntity(
          contentId: contentIdParam,
          path: pathParam,
          contentName: contentNameParam,
          imageDescription: imageDescriptionParam,
          scannedImageTexts: scannedImageTextsParam,
          contentSizeInBytes: contentSizeInBytesParam,
          extension: extensionParam,
          type: typeParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
    ContentEmbeddingsEntity: obx_int.EntityDefinition<ContentEmbeddingsEntity>(
      model: _entities[1],
      toOneRelations: (ContentEmbeddingsEntity object) => [],
      toManyRelations: (ContentEmbeddingsEntity object) => {},
      getId: (ContentEmbeddingsEntity object) => object.id,
      setId: (ContentEmbeddingsEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ContentEmbeddingsEntity object, fb.Builder fbb) {
        final contentIdOffset = fbb.writeString(object.contentId);
        final contentVectorsOffset = fbb.writeListFloat32(
          object.contentVectors,
        );
        final contentTypeOffset = fbb.writeString(object.contentType);
        fbb.startTable(5);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, contentIdOffset);
        fbb.addOffset(2, contentVectorsOffset);
        fbb.addOffset(3, contentTypeOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final contentIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final contentTypeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final contentVectorsParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGet(buffer, rootOffset, 8, []);
        final object = ContentEmbeddingsEntity(
          contentId: contentIdParam,
          contentType: contentTypeParam,
          contentVectors: contentVectorsParam,
        )..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ContentsEntity] entity fields to define ObjectBox queries.
class ContentsEntity_ {
  /// See [ContentsEntity.id].
  static final id = obx.QueryIntegerProperty<ContentsEntity>(
    _entities[0].properties[0],
  );

  /// See [ContentsEntity.contentId].
  static final contentId = obx.QueryStringProperty<ContentsEntity>(
    _entities[0].properties[1],
  );

  /// See [ContentsEntity.path].
  static final path = obx.QueryStringProperty<ContentsEntity>(
    _entities[0].properties[2],
  );

  /// See [ContentsEntity.contentName].
  static final contentName = obx.QueryStringProperty<ContentsEntity>(
    _entities[0].properties[3],
  );

  /// See [ContentsEntity.extension].
  static final extension = obx.QueryStringProperty<ContentsEntity>(
    _entities[0].properties[4],
  );

  /// See [ContentsEntity.type].
  static final type = obx.QueryStringProperty<ContentsEntity>(
    _entities[0].properties[5],
  );

  /// See [ContentsEntity.contentSizeInBytes].
  static final contentSizeInBytes = obx.QueryIntegerProperty<ContentsEntity>(
    _entities[0].properties[6],
  );

  /// See [ContentsEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<ContentsEntity>(
    _entities[0].properties[7],
  );

  /// See [ContentsEntity.updatedAt].
  static final updatedAt = obx.QueryDateProperty<ContentsEntity>(
    _entities[0].properties[8],
  );

  /// See [ContentsEntity.imageDescription].
  static final imageDescription = obx.QueryStringProperty<ContentsEntity>(
    _entities[0].properties[9],
  );

  /// See [ContentsEntity.scannedImageTexts].
  static final scannedImageTexts = obx.QueryStringProperty<ContentsEntity>(
    _entities[0].properties[10],
  );
}

/// [ContentEmbeddingsEntity] entity fields to define ObjectBox queries.
class ContentEmbeddingsEntity_ {
  /// See [ContentEmbeddingsEntity.id].
  static final id = obx.QueryIntegerProperty<ContentEmbeddingsEntity>(
    _entities[1].properties[0],
  );

  /// See [ContentEmbeddingsEntity.contentId].
  static final contentId = obx.QueryStringProperty<ContentEmbeddingsEntity>(
    _entities[1].properties[1],
  );

  /// See [ContentEmbeddingsEntity.contentVectors].
  static final contentVectors = obx.QueryHnswProperty<ContentEmbeddingsEntity>(
    _entities[1].properties[2],
  );

  /// See [ContentEmbeddingsEntity.contentType].
  static final contentType = obx.QueryStringProperty<ContentEmbeddingsEntity>(
    _entities[1].properties[3],
  );
}
