AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI backend for Vectora Project

Globals:
  Function:
    Runtime: python3.13
    Timeout: 60
    MemorySize: 1024
    Architectures:
      - x86_64

Resources:
  VectoraProjectApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      BinaryMediaTypes:
        - multipart/form-data
        - image/png
        - image/jpeg
        - image/jpg

  VectoraBackendLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src.main.handler
      CodeUri: .
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
        - arn:aws:iam::636052469132:policy/VectoraProdReadSSMParameters
      Environment:
        Variables:
          REFRESH_TOKEN_EXPIRE_DAYS: "0"
          ACCESS_TOKEN_EXPIRE_MINUTES: "0"
          VOYAGE_AI_API_SECRET: ""
          JWT_SECRET_KEY: ""
          GEMINI_API_KEY: ""
          OPEN_ROUTER_API_KEY: ""
          COHERE_API_KEY: ""
      Events:
        # Root path
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref VectoraProjectApi
            Path: /
            Method: ANY
        # Proxy for all other routes
        Proxy:
          Type: Api
          Properties:
            RestApiId: !Ref VectoraProjectApi
            Path: /{proxy+}
            Method: ANY
  # Daily Ads Quota Reset (12:00 AM IST)
  VectoraDailyQuotaScheduler:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: VectoraDailyAdsQuotaReset
      Description: "Reset daily ads quota for all users at 12:00 AM IST"
      ScheduleExpression: "cron(0 0 * * ? *)"
      ScheduleExpressionTimezone: "Asia/Kolkata"
      FlexibleTimeWindow:
        Mode: "OFF"
      Target:
        Arn: !GetAtt VectoraBackendLambda.Arn
        RoleArn: arn:aws:iam::636052469132:role/EventbridgeSchedulerLambdaInvokeRole
        Input: "{}"